import React,{Component} from "react"
class Hello extends Component{
    render(){
        return(
            <div>
                <h3>SBi</h3>
                <table>
                    <tr>
                        <th>Name</th>
                        <th>Id no</th>
                        <th>Phone no</th>
                    </tr>
                    <tr>
                        <td>Ravi</td>
                        <td>123@</td>
                        <td>9160613650</td>
                    </tr>
                    <tr>
                        <td>Ravi</td>
                        <td>124@</td>
                        <td>45678</td>
                        </tr>
                </table>



            </div>
        )
    }
}